modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"

[[mods]]
modId = "simplescreens"
version = "${file.jarVersion}"
displayName = "SimpleScreens"
description = '''
Allows customizing the background of loading screens.
'''

[[dependencies.simplescreens]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.simplescreens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "CLIENT"
